git:
  depth: 5

stages:
  - "Build and Test"
  - "Package"
  - "Deployment"

jobs:
  include:
    - stage: "Build and Test"
      language: java
      jdk: oraclejdk11
      before_script:
        - cd sample-application-backend
      script:
        - echo "Maven build & test"
        - mvn clean verify 
        - echo "Run test coverage"
        - mvn org.jacoco:jacoco-maven-plugin:prepare-agent
        - echo "Run Quality Gate"
        - mvn sonar:sonar -Dsonar.projectKey=vebervi-cpe_sample-application-students
    - stage: "Build and Test"
      language: node.js
      node_js: "12.20"
      before_script:
        - cd sample-application-frontend
      script:
        - echo "NPM install and build"
        - npm install
        - npm run build
        - npm run lint
    - stage: "Package"
      before_script:
        - cd sample-application-backend
      script:
        - echo "Docker build ..."
        - docker build -t $DOCKERHUB_USER/backend .
        - echo "Docker login ..."
        - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PWD
        - echo "Docker push ..."
        - docker push $DOCKERHUB_USER/backend
    - stage: "Package"
      before_script:
        - cd sample-application-frontend
      script:
        - echo "Docker build ..."
        - docker build -t $DOCKERHUB_USER/frontend .
        - echo "Docker login ..."
        - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PWD
        - echo "Docker push ..."
        - docker push $DOCKERHUB_USER/frontend
    - stage: "Deployment"
      before_script:
        - cd ansible
        - sudo apt-add-repository --yes --update ppa:ansible/ansible
        - sudo apt-get install ansible
      script:
        - echo "Create temp file ssh_key"
        - echo $SSH_KEY >> ssh_key
        - echo "Change rights on ssh_key"
        - sudo chmod 600 ssh_key
        - echo "Ansible playbook ..."
        - ansible-playbook -v -i inventories/setup.yml playbook.yml
        - echo "Remove temp file ssh_key"
        - rm ssh_key

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.npm"

services:
  - docker

addons:
  sonarcloud:
    organization: "vebervi-cpe"
    token: "$SONARCLOUD_TOKEN"
