all:
  vars:
    ansible_user: centos
    ansible_ssh_private_key_file: ../ssh_key
    # ansible_ssh_private_key_file: /home/osboxes/Documents/DevOps/Seance3_cleRSA/id_rsa
  children:
    prod:
      hosts: vincent.veber.takima.cloud